### PR TITLE
adding get-loaded-partition-info-list command

### PR DESCRIPTION
**Pull request by mrdakj**
Fixes # .

Changes include:

- Adding new command to get top/leas loaded partitions.

Verified:

- [ ] Build and test CI passes
- [ ] History and readme updated to reflect changes
- [ ] Package version updated according to semantic versioning rules
- [ ] Tests modified or added, when applicable
- [ ] Updated code owners file, when applicable
- [ ] Read the [PR checklist](https://github.com/Azure/service-fabric-cli/wiki/Checklist)

### CODE REVIEW

**Review by jeffj6123 — APPROVED** [review]

**Comment by jeffj6123** [comment]
@mrdakj the API version is 7.3. Are the changes here meant for release with 7.2?

**Comment by mrdakj** [comment]
> @mrdakj the API version is 7.3. Are the changes here meant for release with 7.2?

No, this is meant for the next release.

**Comment by jeffj6123** [comment]
@mrdakj can you try recreating the PR, im not sure why the CI isnt starting.

**Comment by jeffj6123** [comment]
@mrdakj looking at the swagger spec released for 7.2, I dont see this API in there. I see it added for the next version 7.3/8.0.

**Comment by mrdakj** [comment]
> @mrdakj looking at the swagger spec released for 7.2, I dont see this API in there. I see it added for the next version 7.3/8.0.

Yes. API is meant for 8.0 version.

**Comment by mrdakj** [comment]
@jeffj6123 , is API version fine?

**Pull request closed without merging**
