### PR TITLE
Adding move-primary, move-secondary and move-instance commands

### PR DESCRIPTION
**Pull request by acukanovic**
Fixes # .

Changes include:

- Adding command move-primary for moving primary replica (present in SF v6.5)
- Adding command move-secondary for moving secondary replica (present in SF v6.5)
- Adding command move-instance for moving stateless instance (present in SF v8.0)

Verified:

- [ ] Build and test CI passes
- [ ] History and readme updated to reflect changes
- [ ] Package version updated according to semantic versioning rules
- [ ] Tests modified or added, when applicable
- [ ] Updated code owners file, when applicable
- [ ] Read the [PR checklist](https://github.com/Azure/service-fabric-cli/wiki/Checklist)

### CODE REVIEW

**Comment by jeffj6123** [comment]
@acukanovic we can add the 6.5+ API commands but not the 8.0 one because we should not add commands that are not usable until the next major release. We can add the 8.0 commands much closer to when we would be releasing for 8.0

**Comment by acukanovic** [comment]
@jeffj6123 got it. I am fine with waiting release 8.0 to check in all three commands. There's no hurry to check in 6.5 commands now. If you agree, let's leave this PR open until March when 8.0 is planned to be released.

**Comment by acukanovic** [comment]
@jeffj6123 code complete for 8.0 is February 26th. When do you suggest we complete this PR?

**Comment by jeffj6123** [comment]
@acukanovic  we can get it started now.

**Comment by acukanovic** [comment]
@jeffj6123 great. I see that the PR SFCTL build failed as move-instance is not recognized while move primary and move secondary which are dated in 6.5 are. I pulled my branch acukanovic/service-fabric-cli and I have the same issues when testing locally. However, at the time this PR was published I successfully tested move instance capability. I've tried following guidelines to swap python sdk from swagger build today in hope to resolve this, but I wasn't able to successfully build Swagger. You can find the error below. Could you help me out here? How can I proceed?

 "D:\swagger\src\dirs.proj" (default target) (1) ->
       "D:\swagger\src\spec\dirs.proj" (VerifyAlteredTargetsUsed;Build target) (2) ->
       "D:\swagger\src\spec\sfclient\dirs.proj" (VerifyAlteredTargetsUsed;Build target) (3) ->
       "D:\swagger\src\spec\sfclient\python_sdk\swagger-sfclient_python_sdk.proj" (VerifyAlteredTargetsUsed;Build targe
       t) (6) ->
       (GeneratePythonSDK target) ->
         EXEC : error : Package '@autorest/python' - '5.6.3' failed to install: [D:\swagger\src\spec\sfclient\python_sd
       k\swagger-sfclient_python_sdk.proj]
         Failed to install package 'https : //registry.npmjs.org/@autorest/python/-/python-5.6.3.tgz' -- error : Proces
       s Failed.Error: Failed to install package 'https://registry.npmjs.org/@autorest/python/-/python-5.6.3.tgz' -- Er
       ror: Process Failed. [D:\swagger\src\spec\sfclient\python_sdk\swagger-sfclient_python_sdk.proj]
         D:\swagger\src\spec\sfclient\python_sdk\swagger-sfclient_python_sdk.proj(40,7): error MSB3073: The command ""D
       :\CxCache\sf.autorest.1.0.3\bin\run_autorest.cmd" "D:\swagger\src\spec\sfclient\src\readme.md" --python --azure-
       arm=true --payload-flattening-threshold=2 --license-header=MICROSOFT_MIT_NO_VERSION --namespace=azure.servicefab
       ric --package-name=azure-servicefabric --output-folder="D:\swagger\src\spec\sfclient\python_sdk\objd\AMD64\pytho
       n_sdk" --input-file="D:\swagger\out\debug-AMD64\swagger-sfclient\7.2.0\spec\servicefabric.json"" exited with cod
       e 1.

**Comment by jeffj6123** [comment]
what version of python do you have installed on the machine?

**Comment by acukanovic** [comment]
@jeffj6123 , I have these two. The first one is 3.6.6, second one is 2.7

image

**Comment by acukanovic** [comment]
@jeffj6123 I managed to test my changes locally. I followed instructions https://github.com/microsoft/service-fabric-cli/wiki/Internal-development and uploaded customSDK from my Swagger build so now move_instance tests are passing.

However, my SFCTL builds are failing due to other error:
TypeError: __init__() missing 1 required keyword-only argument: 'use_only_primary_load'

It seems to be related to your newest change to the Swagger repo: https://msazure.visualstudio.com/One/_git/SF-Swagger/commit/a25761f034c9f1ef14bc22c36e5012583798bea3?refName=refs%2Fheads%2Fdevelop. 

Can you please fix CLI tests to pass with your new change?

Also, please let me know if customSDK for 8.0 should be checked in by me within this PR or there's separate procedure for that?

**Comment by acukanovic** [comment]
@jeffj6123 I rebased your recent SDK CLI change, rebuild fresh Swagger, uploaded sdk to customSDK and pushed new iteration. Now all builds are passing but travis CI check is still not completed. Is there anything else I need to do on my side to complete it?

**Pull request merged**
